### ISSUE TITLE
Any plan to add CTCF motifs updated in JASPAR 2022?

### ISSUE THREAD

**Issue by wangfuzhou110** [mdozmorov/CTCF#1]
Dear Dr. Dozmorov,

I wonder whether you have any plan to incorporate [MA1929.1](https://testjaspar.uio.no/matrix/MA1929.1) and [MA1930.1](https://testjaspar.uio.no/matrix/MA1930.1) in this repo? These are new entries updated in JASPAR 2022.

By the way, may I ask another question -- as you mention in the README, this AnnotationHub can be used for both human and mouse genomes. However, in JASPAR these entries are only marked as Homo Sapiens profiles. So why can we use this repo for mouse? Could we extend these data to more mammals?

I would appreciate it very much if you could kindly answer these questions.

Fuzhou

**Comment by mdozmorov** [comment]
Good point, we'll add these matrices.  Thanks, Fuzhou. 

As for human and mouse - there are genomic coordinates of [MA0139.1](https://jaspar.genereg.net/matrix/MA0139.1/) found in human (hg19, hg38) and mouse (mm9, mm10) genomes. This, and other matrices can be scanned for in genomes of any organism. We just kept it to human/mouse for now. If you have other requests, please, add here. 

There are more plans to add CTCF sites from other databases. Stay tuned!

**Comment by wangfuzhou110** [comment]
That's excellent! Thank you. I'll comment here or create a pull request if other organisms are of interest.
