### ISSUE TITLE
Inquiries on PWM to meme

### ISSUE THREAD

**Issue by distilledchild** [mdozmorov/CTCF#2]
Dear @mdozmorov 

Thank you for your amazing work for the package. I wanted to convert PWMs from datasets you used, Jaspar2022, HOCOMOCO v11, SwissRegulon, Jolma 2013, CTCFBSDB and CIS-BP to meme format in order to find out motifs in rat using FIMO, but I cound't do PWMs from CTCFBSDB. Could you give me some advice on how to convert PWMs to MEME format please?

**Comment by mdozmorov** [comment]
Hi, this is beyond what our package does, but this package may help you https://bioconductor.org/packages/universalmotif/
